#include "Framework.h"

string GetD3D11ReturnMessage( HRESULT Hr )
{
	switch( Hr )
	{
	case D3D11_ERROR_FILE_NOT_FOUND:
		return "D3D11_ERROR_FILE_NOT_FOUND";
	case D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS :
		return "D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS";
	case D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD :
		return "D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD";
	// case D3DERR_INVALIDCALL :
	// 	return "D3DERR_INVALIDCALL";
	case DXGI_ERROR_WAS_STILL_DRAWING  :
		return "DXGI_ERROR_WAS_STILL_DRAWING";
	case E_FAIL  :
		return "E_FAIL";
	case E_INVALIDARG :
		return "E_INVALIDARG";
	case E_OUTOFMEMORY :
		return "E_OUTOFMEMORY";
	case E_NOTIMPL :
		return "E_NOTIMPL";
	case S_FALSE :
		return "S_FALSE";
	default:
		return "S_OK";
	}
}
